add didimputation
conda-forge/r-didimputation-feedstock pull request #2
Opened 2023-04-12 14:21 UTC by okankcb

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-04-13 06:35 UTC, okankcb commented
@conda-forge-admin please rerender

2023-04-14 10:04 UTC, okankcb commented
@conda-forge/r

2023-04-14 16:05 UTC, mfansler requested changes
Please use informative commit messages and describe the intent of this PR with a proper title and a brief statement.

2023-04-14 16:05 UTC, mfansler commented on .azure-pipelines/azure-pipelines-win.yml
You should not manually edit any rendered files. The feedstock should be in fully working condition after a rerender.

2023-04-14 16:05 UTC, mfansler commented on recipe/conda_build_config.yaml
> + - 4.0
Conda Forge does not support R 4.2 for **win** platform. Please follow two space indentation for YAML files.

You must rerender after merging this suggestion:

```suggestion
  - 4.2  # [not win]
  - 4.1
  - 4.0
```

2023-04-17 08:02 UTC, okankcb commented
@conda-forge-admin please rerender

2023-04-17 08:20 UTC, okankcb commented
@conda-forge-admin please rerender

2023-04-17 23:44 UTC, mfansler approved these changes

2023-04-17 23:44 UTC, merged